on: [push, pull_request]

name: Test & Doc

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      - uses: actions/checkout@v2
      - name: Install capnp
        run: sudo apt-get install capnproto -y
      - name: Build docs
        run: |
          cargo doc

      - name: Deploy 🚀
        if: github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
            ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
            BRANCH: gh-pages # The branch the action should deploy to.
            FOLDER: target/doc # The folder the action should deploy.
